// Generated by CoffeeScript 1.6.3
(function() {
  var _;

  _ = require('../vendor/lodash/dist/lodash');

  _.mixin({
    joinURIComponents: function() {
      var components, uri, _ref;
      components = _.map(arguments, function(str, i) {
        if (str != null) {
          return _.trim(str, '/').split(/\/(?!\/)/);
        }
      });
      uri = ((_ref = arguments[0]) != null ? _ref[0] : void 0) === '/' ? '/' : '';
      return uri += _.flatten(_.compact(components)).join('/');
    },
    trim: function(string, characters) {
      var regexp;
      if (characters == null) {
        characters = '\\s';
      }
      regexp = new RegExp("^[" + characters + "]+|[" + characters + "]+$", 'g');
      return string.replace(regexp, '');
    }
  });

  module.exports = _;

}).call(this);
