// Generated by CoffeeScript 1.6.3
(function() {
  var _;

  _ = require('../vendor/lodash/dist/lodash');

  _.mixin({
    joinURIComponents: function() {
      var components;
      components = _.map(arguments, function(str) {
        return str != null ? str.split(/\/(?!\/)/) : void 0;
      });
      return _.flatten(_.compact(components)).join('/');
    }
  });

  module.exports = _;

}).call(this);
